src/Entity/Students.php
<?php

namespace App\Entity;

use App\Repository\StudentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentsRepository::class)]
class Students
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birth_date = null;

    #[ORM\ManyToOne]
    private ?Classes $class = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getClass(): ?Classes
    {
        return $this->class;
    }

    public function setClass(?Classes $class): static
    {
        $this->class = $class;

        return $this;
    }
}

src/Form/StudentsType.php
<?php

namespace App\Form;

use App\Entity\Classes;
use App\Entity\Students;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('last_name')
            ->add('first_name')
            ->add('birth_date', null, [
                'widget' => 'single_text',
            ])
            ->add('class', EntityType::class, [
                'class' => Classes::class,
                'choice_label' => 'name',
                'label' => 'Class',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Students::class,
        ]);
    }
}

src/Controller/StudentsController.php
<?php

namespace App\Controller;

use App\Entity\Students;
use App\Form\StudentsType;
use App\Repository\StudentsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/students')]
#[IsGranted('ROLE_USER')]
final class StudentsController extends AbstractController
{
    #[Route(name: 'app_students_index', methods: ['GET'])]
    public function index(StudentsRepository $studentsRepository): Response
    {
        return $this->render('students/index.html.twig', [
            'students' => $studentsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_students_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $student = new Students();
        $form = $this->createForm(StudentsType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($student);
            $entityManager->flush();

            return $this->redirectToRoute('app_students_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('students/new.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_students_show', methods: ['GET'])]
    public function show(Students $student): Response
    {
        return $this->render('students/show.html.twig', [
            'student' => $student,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_students_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Students $student, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StudentsType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_students_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('students/edit.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_students_delete', methods: ['POST'])]
    public function delete(Request $request, Students $student, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$student->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($student);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_students_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/students/_delete_form.html.twig
<form method="post" action="{{ path('app_students_delete', {'id': student.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ student.id) }}">
    <button class="btn">Delete</button>
</form>

templates/students/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/students/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Students{% endblock %}

{% block body %}
    <h1>Edit Students</h1>

    {{ include('students/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_students_index') }}">back to list</a>

    {{ include('students/_delete_form.html.twig') }}
{% endblock %}

templates/students/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Students index{% endblock %}

{% block body %}
    <h1>Students index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Last_name</th>
                <th>First_name</th>
                <th>Birth_date</th>
                <th>Class</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.lastName }}</td>
                <td>{{ student.firstName }}</td>
                <td>{{ student.birthDate ? student.birthDate|date('Y-m-d') : '' }}</td>
                <td>{{ student.class.name }}</td>
                <td>
                    <a href="{{ path('app_students_show', {'id': student.id}) }}">show</a>
                    <a href="{{ path('app_students_edit', {'id': student.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_students_new') }}">Create new</a>
{% endblock %}

templates/students/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Students{% endblock %}

{% block body %}
    <h1>Create new Students</h1>

    {{ include('students/_form.html.twig') }}

    <a href="{{ path('app_students_index') }}">back to list</a>
{% endblock %}

templates/students/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Students{% endblock %}

{% block body %}
    <h1>Students</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ student.id }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ student.lastName }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ student.firstName }}</td>
            </tr>
            <tr>
                <th>Birth_date</th>
                <td>{{ student.birthDate ? student.birthDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_students_index') }}">back to list</a>

    <a href="{{ path('app_students_edit', {'id': student.id}) }}">edit</a>

    {{ include('students/_delete_form.html.twig') }}
{% endblock %}